---
title: "Fiscal Performance data cleaning dataset"
author: "Alvaro Guijarro"
date: "`r Sys.Date()`"
output: html_document
---

```{r Libraries, include=Fase}
library(readxl)
library(dplyr)
library(tidyr)
library(tidyverse)
library(plotly)
library(lubridate)
library(ggplot2)
library(forecast)
library(stats)
library(tseries)
library(zoo)
library(writexl)
```

```{r read datasets}
oec_municipios <- read_excel("OEC histórico 2000-2022 municipios.xlsx") 
#Operación Efectiva de Caja 2000-2022, valores en Millions of Pesos / Cash Operations 2000-2022, values in Millions of Pesos
head(oec_municipios)
colnames(oec_municipios)
```

```{r translating column names}
# Set new column names in English with explanations
colnames(oec_municipios) <- c(
  "Order", # Orden: The sequence or order of the data entry.
  "Department", # Departamento: The department or state to which the municipality belongs.
  "Key", # Llave: A unique identifier or key for each entry.
  "MunicipalityCode", # Código Municipio: The unique code for each municipality.
  "city", # Nombre Municipio: The name of the municipality.
  "year", # Año: The year of the data entry.
  "TotalIncome", # Ingresos Totales: Total income received.
  "CurrentIncome", # Ingresos Corrientes: Current (or operational) income.
  "TaxIncome", # Ingresos tributarios: Income received from taxes.
  "PropertyTax", # Predial: Property tax income.
  "IndustryAndCommerceTax", # Industria y comercio: Tax from industry and commerce activities.
  "FuelSurcharge", # Sobretasa a la gasolina: Surcharge on fuel.
  "OtherTaxIncome", # Otros ingresos tributarios: Other tax-related income.
  "NonTaxIncome", # Ingresos No Tributarios: Non-tax related income.
  "CurrentTransfers", # Transferencias corrientes: Current transfers received.
  "NationalLevelCurrentTransfers", # Transferencias corrientes de nivel nacional: Current transfers from the national level.
  "OtherTransfers", # Otras transferencias: Other transfers.
  "TotalExpenses", # GASTOS TOTALES: Total expenses.
  "CurrentExpenses", # Gastos Corrientes: Current (or operational) expenses.
  "OperatingExpenses", # Gastos de funcionamiento: Operating expenses.
  "PersonalServices", # Servicios personales: Expenses on personal services.
  "GeneralExpenses", # Gastos generales: General expenses.
  "TransfersPaid", # Transferencias pagadas: Transfers paid out.
  "PublicDebtInterests", # Intereses de la deuda pública: Interests on public debt.
  "CurrentDissaving/Saving", # Desahorro/Ahorro corriente: Current dissaving or saving.
  "CapitalIncome", # Ingresos de Capital: Income from capital.
  "Royalties", # Regalías: Income from royalties.
  "NationalTransfers", # Transferencias nacionales: Transfers from the national level.
  "Co-financing", # Cofinanciación: Co-financing.
  "OtherCapitalIncome", # Otros ingresos de capital: Other capital income.
  "CapitalExpenses", # Gastos de Capital: Capital expenses.
  "GrossCapitalFormation", # Formación bruta de capital: Gross capital formation.
  "OtherCapitalExpenses", # Otros gastos de capital: Other capital expenses.
  "TotalDeficitOrSurplus", # Déficit o Superávit Total: Total deficit or surplus.
  "FINANCING", # FINANCIAMIENTO: Financing.
  "NetCredit", # Crédito neto: Net credit.
  "Disbursements", # Desembolsos: Disbursements.
  "Amortizations", # Amortizaciones: Amortizations.
  "BalanceResources_VariationInDepositsAndOthers" # Recursos del Balance, Variación de Depósitos y Otros: Balance resources, variation in deposits, and others.
)
```

```{r filter only relevant cities and deal with Na's}
unique(oec_municipios$city)
cities_to_include <- c("BARRANQUILLA", "BOGOTA D.C.", "BUCARAMANGA", 
                       "CALI", "CARTAGENA", "CUCUTA", "IBAGUE", "MANIZALES", "MEDELLIN", 
                       "MONTERIA", "PASTO", "PEREIRA", "VILLAVICENCIO")
oec_municipios_filtered <- oec_municipios[oec_municipios$city %in% cities_to_include, ]

#Set Na's to 0 
oec_municipios_filtered <- oec_municipios_filtered %>%
  mutate(across(where(is.numeric), ~replace_na(., 0)), # Replace NA with 0 in numeric columns
         across(where(is.character), ~replace_na(., ""))) # Replace NA with empty string in character columns


# View the filtered dataset
head(oec_municipios_filtered)
unique(oec_municipios_filtered$city)

# Identify rows with any empty cells (NA values)
rows_with_empty_cells <- oec_municipios_filtered %>% 
  filter(apply(., 1, anyNA))

# View the rows with empty cells
rows_with_empty_cells


city_transform <- c(
  "BARRANQUILLA" = "BARRANQUILLA A.M.",
  "BOGOTA D.C." = "BOGOTÁ D.C.",
  "BUCARAMANGA" = "BUCARAMANGA A.M.",
  "CALI" = "CALI A.M.",
  "CARTAGENA" = "CARTAGENA",
  "CUCUTA" = "CÚCUTA A.M.",
  "IBAGUE" = "IBAGUÉ",
  "MANIZALES" = "MANIZALES A.M.",
  "MEDELLIN" = "MEDELLÍN A.M.",
  "MONTERIA" = "MONTERÍA",
  "PASTO" = "PASTO",
  "PEREIRA" = "PEREIRA A.M.",
  "VILLAVICENCIO" = "VILLAVICENCIO"
)
oec_municipios_filtered <- oec_municipios_filtered %>%
  mutate(city = recode(city, !!!city_transform))  %>%
  arrange(city, year) %>%
  select(-Order,-Department,-Key,-MunicipalityCode)
```

```{r visualize the data}
# Define the list of variables to loop over
variables_list <- c("TotalIncome", "CurrentIncome","TaxIncome","PropertyTax", "IndustryAndCommerceTax","FuelSurcharge", "OtherTaxIncome", "NonTaxIncome", "CurrentTransfers", "NationalLevelCurrentTransfers","OtherTransfers","TotalExpenses","CurrentExpenses","OperatingExpenses","PersonalServices","GeneralExpenses",
  "TransfersPaid","PublicDebtInterests", "CurrentDissaving/Saving","CapitalIncome","Royalties","NationalTransfers","Co-financing","OtherCapitalIncome", "CapitalExpenses","GrossCapitalFormation","OtherCapitalExpenses","TotalDeficitOrSurplus","FINANCING","NetCredit","Disbursements","Amortizations", "BalanceResources_VariationInDepositsAndOthers")

# Create the interactive plot directly with plotly
plotly_obj <- plot_ly(data = oec_municipios_filtered, x = ~year, y = ~TotalIncome, 
                      color = ~city, colors = RColorBrewer::brewer.pal(n = 8, name = "Dark2"),
                      type = 'scatter', mode = 'lines+markers',
                      text = ~city, hoverinfo = 'text+x+y') %>%
  layout(title = "Total Income by City from 2000 to 2022",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Income, values in $ Millions of Pesos", tickformat = ",d", 
                      range = c(0, max(oec_municipios_filtered$TotalIncome, na.rm = TRUE))),
         legend = list(orientation = "v", x = 1.05, y = 1))

# Display the interactive plot
plotly_obj
```

```{r}
# Loop over each variable and create a plot
plot_list <- lapply(variables_list, function(variable) {
  # Filter the dataset for the variable
  data_variable <- oec_municipios_filtered %>%
    select(city, year, value = .data[[variable]])
  
  # Start the plot with non-December data
  p <- plot_ly(data = data_variable, 
               x = ~year, y = ~value, 
               color = ~city, colors = RColorBrewer::brewer.pal(n = 8, name = "Dark2"),
               type = 'scatter', mode = 'lines+markers',
               text = ~city, hoverinfo = 'text+x+y') 

  # Layout settings
  p <- layout(p,
              title = paste("Monthly", gsub("_", " ", variable), "Evolution by City"),
              xaxis = list(title = "Date"),
              yaxis = list(title = paste(gsub("_", " ", variable)),
                        range = c(0, max(oec_municipios_filtered[[variable]], na.rm = TRUE))),
              legend = list(orientation = 'v', x = 1.05, y = 1))
  
  return(p)
})

# Print the plots
for (plot in plot_list) {
  print(plot)
}
```


Let's Interpolate the data to have it in a monthly basis
```{r}
# Function to interpolate all specified columns for a single city
interpolate_city <- function(data_city, columns_to_interpolate) {
  if (nrow(data_city) > 0) {
    # Assume city name and city_id are the same for all rows, as it's grouped
    city_name <- unique(data_city$city)[1]
    
    # Create an annual time series with NA handling
    annual_dates <- as.Date(paste(data_city$year, "-12-01", sep = ""))
    
    # Create a sequence of monthly dates from the start to the end of the series
    monthly_dates <- seq(from = min(annual_dates), to = max(annual_dates), by = "1 month")
    
    # Initialize the monthly data with the correct number of rows
    monthly_data <- data.frame(
      city = rep(city_name, length(monthly_dates)),
      date = monthly_dates,
      year = format(monthly_dates, "%Y"),
      month = format(monthly_dates, "%m")
    )
    
    for (col in columns_to_interpolate) {
      # Create an annual time series for the current column
      annual_series <- zoo(data_city[[col]], order.by = annual_dates)
      
      # Use na.approx only on the interior NAs and not on leading/trailing NAs
      annual_series <- na.approx(annual_series, na.rm = FALSE)
      
      # Perform spline interpolation
      monthly_series <- na.spline(annual_series, xout = monthly_dates)
      
      # Ensure that interpolated values are not negative
      monthly_series[monthly_series < 0] <- 0
      
      # Add the monthly series to the monthly data
      monthly_data[[col]] <- coredata(monthly_series)
    }
    
    return(monthly_data)
  } else {
    return(data.frame()) # Return an empty data.frame if there is no data
  }
}

# Define the columns to interpolate
columns_to_interpolate <- c("TotalIncome", 
  "CurrentIncome", 
  "TaxIncome", 
  "PropertyTax", 
  "IndustryAndCommerceTax", 
  "FuelSurcharge", 
  "OtherTaxIncome", 
  "NonTaxIncome", 
  "CurrentTransfers", 
  "NationalLevelCurrentTransfers", 
  "OtherTransfers", 
  "TotalExpenses", 
  "CurrentExpenses", 
  "OperatingExpenses", 
  "PersonalServices", 
  "GeneralExpenses", 
  "TransfersPaid", 
  "PublicDebtInterests", 
  "CurrentDissaving/Saving", 
  "CapitalIncome", 
  "Royalties", 
  "NationalTransfers", 
  "Co-financing", 
  "OtherCapitalIncome", 
  "CapitalExpenses", 
  "GrossCapitalFormation", 
  "OtherCapitalExpenses", 
  "TotalDeficitOrSurplus", 
  "FINANCING", 
  "NetCredit", 
  "Disbursements", 
  "Amortizations", 
  "BalanceResources_VariationInDepositsAndOthers")

# Apply the interpolation to each city and combine the results
monthly_data <- oec_municipios_filtered %>%
  group_by(city) %>%
  group_map(~interpolate_city(.x, columns_to_interpolate), .keep = TRUE) %>%
  bind_rows()

#Filter the data by date range
monthly_data <- monthly_data %>%
   filter(date >= as.Date("2000-12-01") & date <= as.Date("2023-12-31"))
head(monthly_data)
```
```{r}
# Add a new column to identify December months
monthly_data$Is_December <- format(monthly_data$date, "%m") == "12"

# Define the list of variables to loop over
variables_list <- c("TotalIncome", "CurrentIncome","TaxIncome","PropertyTax", "IndustryAndCommerceTax","FuelSurcharge", "OtherTaxIncome", "NonTaxIncome", "CurrentTransfers", "NationalLevelCurrentTransfers","OtherTransfers","TotalExpenses","CurrentExpenses","OperatingExpenses","PersonalServices","GeneralExpenses",
  "TransfersPaid","PublicDebtInterests", "CurrentDissaving/Saving","CapitalIncome","Royalties","NationalTransfers","Co-financing","OtherCapitalIncome", "CapitalExpenses","GrossCapitalFormation","OtherCapitalExpenses","TotalDeficitOrSurplus","FINANCING","NetCredit","Disbursements","Amortizations", "BalanceResources_VariationInDepositsAndOthers")

# Loop over each variable and create a plot
plot_list <- lapply(variables_list, function(variable) {
  # Filter the dataset for the variable
  data_variable <- monthly_data %>%
    select(city, date, value = .data[[variable]], Is_December)
  
  # Start the plot with non-December data
  p <- plot_ly(data = data_variable %>% filter(!Is_December), 
               x = ~date, y = ~value, 
               color = ~city, colors = RColorBrewer::brewer.pal(n = 8, name = "Dark2"),
               type = 'scatter', mode = 'lines+markers',
               text = ~city, hoverinfo = 'text+x+y') 
  
  # Add December data with black outlines
  p <- add_trace(p, data = data_variable %>% filter(Is_December), 
                 x = ~date, y = ~value,
                 marker = list(line = list(color = 'black', width = 2)),
                 type = 'scatter', mode = 'markers')

  # Layout settings
  p <- layout(p,
              title = paste("Monthly", gsub("_", " ", variable), "Evolution by City"),
              xaxis = list(title = "Date"),
              yaxis = list(title = paste(gsub("_", " ", variable)),
                        range = c(0, max(monthly_data[[variable]], na.rm = TRUE))),
              legend = list(orientation = 'v', x = 1.05, y = 1))
  
  return(p)
})

# Print the plots
for (plot in plot_list) {
  print(plot)
}
```

```{r}
# Transform the columns to percentages and set their type to double
final_monthly_data <- monthly_data %>%
  mutate(date = format(date, "%Y-%m")) %>%
  # Select all columns except "Is_December"
  select(-Is_December)

# Print the head of the dataset to check the changes
head(final_monthly_data)
```

```{r export dataset}
# Extract the minimum and maximum dates from the dataset
min_date <- min(final_monthly_data$date)
max_date <- max(final_monthly_data$date)

# Create the filename using the min and max dates
filename <- paste0("Fiscal_Performance_cleaned_", min_date, "-", max_date, ".xlsx")

# Write the dataframe to an Excel file
write_xlsx(final_monthly_data, filename)
```

