---
title: "Latitude and Longitude"
author: "Alvaro Guijarro"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(readxl)
library(dplyr)
library(tidyr)
```

```{r}
lal <- read_excel("Colombian cities latitude and longitude.xlsx") 
#Latitud y Longitud de Ciudades de Colombia / Latitude and Longitude of Colombian Cities
lal
unique(lal$city)
```
```{r modification}
municipio_transform <- c(
  "Barranquilla" = "BARRANQUILLA A.M.",
  "Bogotá" = "BOGOTÁ D.C.",
  "Bucaramanga" = "BUCARAMANGA A.M.",
  "Cali" = "CALI A.M.",
  "Cartagena" = "CARTAGENA",
  "Cúcuta" = "CÚCUTA A.M.",
  "Ibagué" = "IBAGUÉ",
  "Manizales" = "MANIZALES A.M.",
  "Medellín" = "MEDELLÍN A.M.",
  "Montería" = "MONTERÍA",
  "Pasto" = "PASTO",
  "Pereira" = "PEREIRA A.M.",
  "Villavicencio" = "VILLAVICENCIO")

lal_cleaned <- lal %>%
  select("city", "lat", "lng", "capital") %>%
  mutate(city = recode(city, !!!municipio_transform))  %>%
  mutate(lat_z = (lat - mean(lat, na.rm = TRUE)) / sd(lat, na.rm = TRUE),
         lng_z = (lng - mean(lng, na.rm = TRUE)) / sd(lng, na.rm = TRUE)) %>%
  filter(city %in% municipio_transform) %>%
  arrange(city)
  
lal_cleaned
```
```{r}
# Create the filename using the min and max dates
filename <- paste0("Latitude_Longitude_cleaned.xlsx")
# Write the dataframe to an Excel file
write_xlsx(lal_cleaned, filename)
```


